language: java

jdk:
  - oraclejdk8    

before_install:
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y libreoffice-writer

install:
  - cd generator
  - mvn -B package
  - java -jar target/resume*.jar -f PDF ../content/resume.xml ../output.pdf
  - cd ..
  - ls -alrt

notifications:
  email: false
