---
name: generate-resume
on:
  push:
    branches:
      - "main"

jobs:
  generate-resume:
    name: |
      generate-resume
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
      pull-requests: read
      actions: read
    steps:
    - name: Checkout Resume Generator sources
      uses: actions/checkout@v3
      with:
        path: "resume-generator"
        fetch-depth: 0

    - name: Checkout resume-generator sources
      uses: actions/checkout@v3
      with:
        path: "resume-generator"
        fetch-depth: 0
      
    - name: Install packages for LibreOffice
      shell: bash
      run: |
        set -euEo pipefail

        sudo add-apt-repository "ppa:libreoffice/ppa"
        sudo apt-get --yes update
        sudo apt-get --yes install "libreoffice" "fonts-ubuntu"

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.11"
        version: "2.7.4"

    - name: Install dependencies for Resume Generator
      shell: bash
      run: |
        set -euEo pipefail
        
        pdm \
          sync \
            --project="./resume-generator/resume-generator"
    
    - name: Generate resume
      shell: bash
      run: |
        set -euEo pipefail

        mkdir -p "./github-pages"

        pdm \
          run \
            --project="./resume-generator/resume-generator" \
              radium226-resume-generator \
                generate \
                  "./resume-generator/data.yml" \
                  "./github-pages/resume.odt"
        
        soffice \
          --convert-to "pdf" \
          --outdir "./github-pages" \
            "./github-pages/resume.odt"

        cat <<EOCAT >"./github-pages/index.html"
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <title>Redirect to Resume</title>
            <meta http-equiv="Refresh" content="0; url='./resume.pdf'" />
          </head>
          <body>
          </body>
        </html>
        EOCAT

        tar -C "./github-pages" -zcvf "./github-pages.tar.gz" "."


    - uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: ./github-pages.tar.gz
