---
name: update-resume
on:
  push:
    branches:
      - "main"
    paths:
      - resume-generator/**
      - headless/**
      - opendocument/**
      - .github/workflow/generate-resume.yml

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
      pull-requests: read
      actions: read
    steps:
    - name: Checkout Resume Generator sources
      uses: actions/checkout@v3
      with:
        path: "resume-generator"
        fetch-depth: 0
      
    - name: Install required Ubuntu packages
      shell: bash
      run: |
        set -euEo pipefail

        sudo add-apt-repository "ppa:libreoffice/ppa"
        sudo apt-get --yes update
        sudo apt-get --yes install "libreoffice" "fonts-ubuntu"
        sudo apt-get --yes install "xvfb" "xdotool" "wmctrl" "openbox" "ffmpeg"

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.11"
        version: "2.7.4"

    - name: Install required Python dependencies
      shell: bash
      run: |
        set -euEo pipefail
        
        pdm sync --project="./resume-generator/resume-generator"

    - name: Check types in Resume Generator
      shell: bash
      run: |
        set -euEo pipefail
        pdm run --project="./resume-generator/resume-generator" check-types 
    
    - name: Test Resume Generator renderers
      shell: bash
      run: |
        set -euEo pipefail
        pdm run --project="./resume-generator/resume-generator" test-renderers 
  
    - uses: actions/upload-artifact@v3
      with:
        name: "test_renderers"
        path: "/tmp/test_renderers"

    - name: Generate resume
      shell: bash
      run: |
        set -euEo pipefail

        mkdir -p "./github-pages"

        pdm \
          run \
            --project="./resume-generator/resume-generator" \
              radium226-resume-generator \
                generate \
                  "./resume-generator/data.yml" \
                  "./github-pages/resume.odt"
        
        soffice \
          --convert-to "pdf" \
          --outdir "./github-pages" \
            "./github-pages/resume.odt"

        cat <<EOCAT >"./github-pages/index.html"
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <title>Redirect to Resume</title>
            <meta http-equiv="Refresh" content="0; url='./resume.pdf'" />
          </head>
          <body>
          </body>
        </html>
        EOCAT

    - uses: actions/upload-pages-artifact@v1
      with:
        path: "./github-pages"

  publish:
    needs: generate

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2    