---
name: generate-resume
on:
  push:
    branches:
      - "main"

jobs:
  generate-resume:
    name: |
      generate-resume
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: read
      actions: read
    steps:
    - name: Checkout Resume Generator sources
      uses: actions/checkout@v3
      with:
        path: "resume-generator"
        fetch-depth: 0

    - name: Checkout resume-generator sources
      uses: actions/checkout@v3
      with:
        path: "resume-generator"
        fetch-depth: 0

    - name: Checkout GitHub Pages
      uses: actions/checkout@v3
      with:
        ref: "gh-pages"
        path: "gh-pages"
        fetch-depth: 0

    - name: Config Git user for GitHub Pages
      shell: bash
      run: |
        git -C "gh-pages" config user.name "GitHub Actions"
        git -C "gh-pages" config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
    - name: Install LibreOffice
      shell: bash
      run: |
        set -euEo pipefail
        sudo add-apt-repository ppa:libreoffice/ppa
        sudo apt-get -y update
        sudo apt-get -y install "libreoffice"

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.11"
        version: "2.7.4"

    - name: Install dependencies for tools/automation
      shell: bash
      run: |
        pdm \
          sync \
            --project="./resume-generator/resume-generator"
    
    - name: Generate resume
      shell: bash
      run: |
        pdm \
          run \
            --project="./resume-generator/resume-generator" \
              radium226-resume-generator \
                generate \
                  "./resume-generator/data.yml" \
                  "./gh-pages/resume.odt"
                  

    - name: Update resume on GitHub Pages
      shell: bash
      run: |
        git -C "./gh-pages" add "./resume.odt"
        git -C "./gh-pages" commit -m "Update resume! "
        git -C "./gh-pages" push -u origin gh-pages